### ISSUE TITLE
ImportError: cannot import name pythontail

### ISSUE THREAD

**Issue by krishnachaitanyareddy** [natanaelfneto/pythontail#3]
Hi,

I am trying to install "pythontail" via pip, it is throwing below error

`pip install pythontail`
`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pythontail
  Using cached https://files.pythonhosted.org/packages/70/97/ebad1dfbc0965d2cd1a4b33bf8c3a6827dd7205e3305a559416eeca255b5/pythontail-0.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-flvVKi/pythontail/setup.py'"'"'; __file__='"'"'/tmp/pip-install-flvVKi/pythontail/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-flvVKi/pythontail/pip-egg-info
         cwd: /tmp/pip-install-flvVKi/pythontail/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-flvVKi/pythontail/setup.py", line 3, in <module>
        from pythontail import pythontail as module
      File "pythontail/__init__.py", line 1, in <module>
        from pythontail import pythontail as tail
    ImportError: cannot import name pythontail
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by natanaelfneto** [comment]
Hi @krishnachaitanyareddy , version 0.8 is fully updated for python3.
